### ISSUE TITLE
Doesn't sample valid tokens?

### ISSUE THREAD

**Issue by ngoodman** [kanishkg/synchromesh#3]
https://github.com/kanishkg/synchromesh/blob/6ca02c27aa25130cd7b092fad5f323f07bc43e6b/synchromesh/synchromesh.py#L61

i think this is always taking the first valid token, not sampling? is that intended?

**Comment by kanishkg** [comment]
Yes, it is intended. The logprobs for now are only intended for inspection, to understand how calibrated the probabilities are for ambiguous inputs.
